### PR TITLE
Added automatic addition of meta data & cover

### PR DESCRIPTION
**Pull request by Capevace**
This PR gives the software the ability, to automatically add the song's meta data to the mp3 file in the ID3 format. It also downloads a the cover of the song and adds that to the meta data as well.

### CODE REVIEW

**Comment by wtfil** [comment]
Hi @Capevace! Thank you for update! Could you pls change the indents to match the original file?

**Comment by Capevace** [comment]
Hey, sorry about that. Should be fixed now!

**Comment by wtfil** [comment]
Cool. Wait few minutes, I will publish new npm package

**Comment by wtfil** [comment]
@Capevace  `google-music-sync@1.7.0`

**Comment by Capevace** [comment]
@wtfil great! thanks.

**Pull request merged**
